Fixes #1957: Ensure unique S3 object keys by adding numeric suffix.
knadh/listmonk pull request #1963
Opened 2024-07-28 20:07 UTC by abhinavxd

- Removed unused functions and variables in filesystem.go

2024-07-29 06:13 UTC, knadh commented
Thanks for the PR!

Thinking about it, rather than each provider implementing its own logic, it'd be simpler to do it centrally in `handleUploadMedia()` and check in the database. Roughly:

- Add a `GetMediaByFilename(fname, provider string)` function to `core/media.go`
- This will require a new query to be added to queries.sql also
- Use this in `handleUploadMedia()` to assert the incoming filename and tweak it if it already exists.
- Remove the existing assertion logic from the filesystem provider.

2024-07-29 06:39 UTC, abhinavxd commented
Yep, makes sense. I will update the PR.

2024-07-29 11:23 UTC, abhinavxd commented
![image](https://github.com/user-attachments/assets/8c5e43f2-28a2-4823-b9fe-0e1886ae5e41)
I added the DB level check for unique filename, but it fails when multiple files with the same name are selected for upload.

The previous provider level check handles this properly.

![image](https://github.com/user-attachments/assets/2f474464-cf8a-4a84-8c97-d95801f0df3b)

2024-07-30 20:29 UTC, abhinavxd commented
@knadh Changes made as discussed.

2024-08-01 18:39 UTC, knadh commented on cmd/utils.go
> +	newName := fmt.Sprintf("%s_%s%s", name, suffix, ext)
Can return from here directly with the variable `newName`.

2024-08-01 18:40 UTC, knadh commented on internal/media/providers/s3/s3.go
> -		ObjectKey: c.makeBucketPath(name),
This doesn't need to change.

2024-08-01 18:41 UTC, knadh requested changes
Couple minor things to fix.

2024-08-01 18:58 UTC, abhinavxd commented
Made the changes requested.

2024-08-08 10:12 UTC, merged